# Analyst-Ready SEC Filings RAG System

**Course:** AI Engineering  
**Professor:** Apostolos Filippas  
**Institution:** Fordham University  
**Team:** Joel Ebukatobi, Claudia Gisemba

This notebook builds a complete SEC 10-K Retrieval-Augmented Generation pipeline for analyst workflows.

In [20]:
%load_ext autoreload
%autoreload 2

In [59]:
# Section 1: Setup & Configuration
import os
import json
import pickle
from pathlib import Path

import numpy as np
import pandas as pd
from dotenv import load_dotenv

from src.ingest import load_raw_filings, filing_stats, load_live_filings
from src.chunk import parse_sections, section_coverage_stats, build_chunks, chunk_stats
from src.embed import embed_chunks, embedding_info
from src.retrieve import HybridRetriever
from src.generate import compare, generate_structured_output
from src.evaluate import build_test_set, run_retrieval_eval, ablation_table

load_dotenv()
OPENAI_API_KEY = os.getenv("OPENAI_API_KEY")
if not OPENAI_API_KEY:
    print("Warning: OPENAI_API_KEY is not set. Generation sections will fail until set.")
else:
    print("OpenAI API key loaded successfully.")

# Global constants for a reproducible project configuration.
CHUNK_SIZE = 800
CHUNK_OVERLAP = 200
TOP_K = 10
EMBED_MODEL = "all-MiniLM-L6-v2"
LLM_MODEL = "gpt-4o-mini"
# TICKERS = ["TSLA", "AAPL", "MSFT", "AMZN", "NVDA"]
# YEAR_RANGE = (2018, 2023)
# TARGET_SECTIONS = ["section_1a", "section_7", "section_3"]

Path("data").mkdir(parents=True, exist_ok=True)
print("Constants defined and environment loaded.")

OpenAI API key loaded successfully.
Constants defined and environment loaded.

In [53]:
TICKERS = ["TSLA", "AAPL", "AMZN", "NVDA", "CCL"]
YEAR_RANGE = (2018, 2025)
TARGET_SECTIONS = ["section_1","section_1a", "section_7", "section_3","section_8"]

## Section 2: Data Ingestion
Load 10-K filings from Hugging Face and normalize into a DataFrame with core metadata.

In [22]:
from src.ingest import load_live_filings, filing_stats

In [23]:
import inspect
print(inspect.getsource(load_live_filings))

def load_live_filings(tickers: Iterable[str], year_range: Tuple[int, int]) -> pd.DataFrame:
    """
    Enhanced Ingestion: Captures structural sections and metadata
    to support the Credit Signal Taxonomy.
    """
    rows = []
    year_min, year_max = year_range

    for ticker in tqdm(tickers, desc="Ingesting SEC Corpus"):
        try:
            company = Company(ticker)
            filings = company.get_filings(form="10-K")
            if not filings:
                continue

            for filing in filings:
                f_year = filing.filing_date.year
                if year_min <= f_year <= year_max:

                    # Get the structured TenK object
                    tenk = filing.obj()

                    # --- SIGNAL TAXONOMY MAPPING ---
                    # Item 1: Business (Business Fragility Signals)
                    item_1 = tenk["Item 1"] or ""

                    # Item 1A: Risk Factors (Risk Disclosure Signals)
                    item_1a = tenk["Item 1A"] or getattr(tenk, "risk_factors", "") or ""

                    # Item 3: Legal (Litigation Escalation Signals)
                    item_3 = tenk["Item 3"] or ""

                    # Item 7: MD&A (Liquidity & Financial Stress Signals)
                    item_7 = tenk["Item 7"] or getattr(tenk, "management_discussion", "") or ""

                    # Item 8: Financials (Debt/Refinancing meta-checks)
                    item_8 = tenk["Item 8"] or ""

                    row = {
                        "ticker": ticker.upper(),
                        "year": f_year,
                        "company": filing.company,
                        "section_1": str(item_1),
                        "section_1a": str(item_1a),
                        "section_3": str(item_3),
                        "section_7": str(item_7),
                        "section_8": str(item_8),
                        # --- META SIGNALS (v1) ---
                        "len_1a": len(str(item_1a)),
                        "len_7": len(str(item_7)),
                        "len_3": len(str(item_3))
                    }

                    # Only add if we have core analytical content
                    if any(len(row[s]) > 500 for s in ["section_1a", "section_7"]):
                        rows.append(row)

        except Exception as e:
            print(f"Skipping {ticker} due to extraction error: {e}")
            continue

    df = pd.DataFrame(rows)
    if not df.empty:
        # Cleanup: Ensure unique filings per year
        df = df.sort_values(["ticker", "year"]).drop_duplicates(subset=["ticker", "year"], keep="last")

    return df.reset_index(drop=True)

In [ ]:
# NOTE: An earlier version used load_raw_filings() from the HuggingFace edgar-corpus dataset.
# That approach was replaced by load_live_filings() which pulls directly from SEC EDGAR
# via the edgartools library, giving us structured section access (Items 1A, 3, 7, 8).

In [26]:
df_test = load_live_filings(tickers=["AAPL"], year_range=(2023, 2024))
print(df_test.columns)

Ingesting SEC Corpus: 100%|██████████| 1/1 [00:22<00:00, 22.65s/it]

Index(['ticker', 'year', 'company', 'section_1', 'section_1a', 'section_3',
       'section_7', 'section_8', 'len_1a', 'len_7', 'len_3'],
      dtype='str')

In [27]:
df_filings = load_live_filings(
    tickers=TICKERS,
    year_range=YEAR_RANGE
)

print("Raw filing DataFrame shape:", df_filings.shape)
display(df_filings.head(3))
display(filing_stats(df_filings).head(20))

Ingesting SEC Corpus:   0%|          | 0/5 [00:00<?, ?it/s]TenK falling back to legacy parser for 'Item 1' (filing: 0001104659-25-042659). New parser sections available: ['part_iii_part_iii', 'part_iii_item_10', 'part_iii_item_11', 'part_iii_item_12', 'part_iii_item_13', 'part_iii_item_14', 'part_iv_part_iv', 'part_iv_item_15']. This fallback will be removed in v6.0.
TenK falling back to legacy parser for 'Item 1A' (filing: 0001104659-25-042659). New parser sections available: ['part_iii_part_iii', 'part_iii_item_10', 'part_iii_item_11', 'part_iii_item_12', 'part_iii_item_13', 'part_iii_item_14', 'part_iv_part_iv', 'part_iv_item_15']. This fallback will be removed in v6.0.
TenK falling back to legacy parser for 'Item 1A' (filing: 0001104659-25-042659). New parser sections available: ['part_iii_part_iii', 'part_iii_item_10', 'part_iii_item_11', 'part_iii_item_12', 'part_iii_item_13', 'part_iii_item_14', 'part_iv_part_iv', 'part_iv_item_15']. This fallback will be removed in v6.0.
TenK falling back to legacy parser for 'Item 3' (filing: 0001104659-25-042659). New parser sections available: ['part_iii_part_iii', 'part_iii_item_10', 'part_iii_item_11', 'part_iii_item_12', 'part_iii_item_13', 'part_iii_item_14', 'part_iv_part_iv', 'part_iv_item_15']. This fallback will be removed in v6.0.
TenK falling back to legacy parser for 'Item 7' (filing: 0001104659-25-042659). New parser sections available: ['part_iii_part_iii', 'part_iii_item_10', 'part_iii_item_11', 'part_iii_item_12', 'part_iii_item_13', 'part_iii_item_14', 'part_iv_part_iv', 'part_iv_item_15']. This fallback will be removed in v6.0.
TenK falling back to legacy parser for 'Item 7' (filing: 0001104659-25-042659). New parser sections available: ['part_iii_part_iii', 'part_iii_item_10', 'part_iii_item_11', 'part_iii_item_12', 'part_iii_item_13', 'part_iii_item_14', 'part_iv_part_iv', 'part_iv_item_15']. This fallback will be removed in v6.0.
TenK falling back to legacy parser for 'Item 8' (filing: 0001104659-25-042659). New parser sections available: ['part_iii_part_iii', 'part_iii_item_10', 'part_iii_item_11', 'part_iii_item_12', 'part_iii_item_13', 'part_iii_item_14', 'part_iv_part_iv', 'part_iv_item_15']. This fallback will be removed in v6.0.
TenK falling back to legacy parser for 'Item 1A' (filing: 0001628280-24-002390). New parser sections available: ['part_ii_item_6', 'part_ii_item_7', 'part_ii_item_7a', 'part_ii_item_8', 'part_ii_item_9', 'part_ii_item_9a', 'part_ii_item_9b', 'part_ii_item_9c', 'part_iii_item_10', 'part_iii_item_11', 'part_iii_item_12', 'part_iii_item_13', 'part_iv_item_15', 'part_iv_item_16', 'part_i_item_1b', 'part_i_item_2', 'part_i_item_3', 'part_i_item_4', 'part_ii_item_5', 'part_i_item_1c', 'part_i_item_1', 'part_iv_item_8']. This fallback will be removed in v6.0.
TenK falling back to legacy parser for 'Item 1' (filing: 0001564590-22-016871). New parser sections available: ['part_iii_item_15', 'part_iii_item_10', 'part_iii_item_11', 'part_iii_item_12', 'part_iii_item_13', 'part_iii_item_14']. This fallback will be removed in v6.0.
TenK falling back to legacy parser for 'Item 1A' (filing: 0001564590-22-016871). New parser sections available: ['part_iii_item_15', 'part_iii_item_10', 'part_iii_item_11', 'part_iii_item_12', 'part_iii_item_13', 'part_iii_item_14']. This fallback will be removed in v6.0.
TenK falling back to legacy parser for 'Item 1A' (filing: 0001564590-22-016871). New parser sections available: ['part_iii_item_15', 'part_iii_item_10', 'part_iii_item_11', 'part_iii_item_12', 'part_iii_item_13', 'part_iii_item_14']. This fallback will be removed in v6.0.
TenK falling back to legacy parser for 'Item 3' (filing: 0001564590-22-016871). New parser sections available: ['part_iii_item_15', 'part_iii_item_10', 'part_iii_item_11', 'part_iii_item_12', 'part_iii_item_13', 'part_iii_item_14']. This fallback will be removed in v6.0.
TenK falling back to legacy parser for 'Item 7' (filing: 0001564590-22-016871). New parser sections available: ['part_iii_item_15', 'part_iii_item_10', 'part_iii_item_11', 'part_iii_item_12', 'part_iii_item_13', 'part_iii_item_14']. This fallback will be removed in v6.0.
TenK falling back to legacy parser for 'Item 7' (filing: 0001564590-22-016871). New parser sections available: ['part_iii_item_15', 'part_iii_item_10', 'part_iii_item_11', 'part_iii_item_12', 'part_iii_item_13', 'part_iii_item_14']. This fallback will be removed in v6.0.
TenK falling back to legacy parser for 'Item 8' (filing: 0001564590-22-016871). New parser sections available: ['part_iii_item_15', 'part_iii_item_10', 'part_iii_item_11', 'part_iii_item_12', 'part_iii_item_13', 'part_iii_item_14']. This fallback will be removed in v6.0.
TenK falling back to legacy parser for 'Item 1' (filing: 0001564590-21-022604). New parser sections available: ['part_iii_item_15', 'part_iii_item_10', 'part_iii_item_11', 'part_iii_item_12', 'part_iii_item_13', 'part_iii_item_14']. This fallback will be removed in v6.0.
TenK falling back to legacy parser for 'Item 1A' (filing: 0001564590-21-022604). New parser sections available: ['part_iii_item_15', 'part_iii_item_10', 'part_iii_item_11', 'part_iii_item_12', 'part_iii_item_13', 'part_iii_item_14']. This fallback will be removed in v6.0.
TenK falling back to legacy parser for 'Item 1A' (filing: 0001564590-21-022604). New parser sections available: ['part_iii_item_15', 'part_iii_item_10', 'part_iii_item_11', 'part_iii_item_12', 'part_iii_item_13', 'part_iii_item_14']. This fallback will be removed in v6.0.
TenK falling back to legacy parser for 'Item 3' (filing: 0001564590-21-022604). New parser sections available: ['part_iii_item_15', 'part_iii_item_10', 'part_iii_item_11', 'part_iii_item_12', 'part_iii_item_13', 'part_iii_item_14']. This fallback will be removed in v6.0.
TenK falling back to legacy parser for 'Item 7' (filing: 0001564590-21-022604). New parser sections available: ['part_iii_item_15', 'part_iii_item_10', 'part_iii_item_11', 'part_iii_item_12', 'part_iii_item_13', 'part_iii_item_14']. This fallback will be removed in v6.0.
TenK falling back to legacy parser for 'Item 7' (filing: 0001564590-21-022604). New parser sections available: ['part_iii_item_15', 'part_iii_item_10', 'part_iii_item_11', 'part_iii_item_12', 'part_iii_item_13', 'part_iii_item_14']. This fallback will be removed in v6.0.
TenK falling back to legacy parser for 'Item 8' (filing: 0001564590-21-022604). New parser sections available: ['part_iii_item_15', 'part_iii_item_10', 'part_iii_item_11', 'part_iii_item_12', 'part_iii_item_13', 'part_iii_item_14']. This fallback will be removed in v6.0.
TenK falling back to legacy parser for 'Item 1' (filing: 0001564590-20-018984). New parser sections available: ['part_iii_item_15', 'part_iii_item_10', 'part_iii_item_11', 'part_iii_item_12', 'part_iii_item_13', 'part_iii_item_14']. This fallback will be removed in v6.0.
TenK falling back to legacy parser for 'Item 1A' (filing: 0001564590-20-018984). New parser sections available: ['part_iii_item_15', 'part_iii_item_10', 'part_iii_item_11', 'part_iii_item_12', 'part_iii_item_13', 'part_iii_item_14']. This fallback will be removed in v6.0.
TenK falling back to legacy parser for 'Item 1A' (filing: 0001564590-20-018984). New parser sections available: ['part_iii_item_15', 'part_iii_item_10', 'part_iii_item_11', 'part_iii_item_12', 'part_iii_item_13', 'part_iii_item_14']. This fallback will be removed in v6.0.
TenK falling back to legacy parser for 'Item 3' (filing: 0001564590-20-018984). New parser sections available: ['part_iii_item_15', 'part_iii_item_10', 'part_iii_item_11', 'part_iii_item_12', 'part_iii_item_13', 'part_iii_item_14']. This fallback will be removed in v6.0.
TenK falling back to legacy parser for 'Item 7' (filing: 0001564590-20-018984). New parser sections available: ['part_iii_item_15', 'part_iii_item_10', 'part_iii_item_11', 'part_iii_item_12', 'part_iii_item_13', 'part_iii_item_14']. This fallback will be removed in v6.0.
TenK falling back to legacy parser for 'Item 7' (filing: 0001564590-20-018984). New parser sections available: ['part_iii_item_15', 'part_iii_item_10', 'part_iii_item_11', 'part_iii_item_12', 'part_iii_item_13', 'part_iii_item_14']. This fallback will be removed in v6.0.
TenK falling back to legacy parser for 'Item 8' (filing: 0001564590-20-018984). New parser sections available: ['part_iii_item_15', 'part_iii_item_10', 'part_iii_item_11', 'part_iii_item_12', 'part_iii_item_13', 'part_iii_item_14']. This fallback will be removed in v6.0.
Ingesting SEC Corpus:  80%|████████  | 4/5 [11:08<02:32, 152.79s/it]TenK falling back to legacy parser for 'Item 1' (filing: 0000815097-20-000020). New parser sections available: ['financial_statements']. This fallback will be removed in v6.0.
TenK falling back to legacy parser for 'Item 1A' (filing: 0000815097-20-000020). New parser sections available: ['financial_statements']. This fallback will be removed in v6.0.
TenK falling back to legacy parser for 'Item 1A' (filing: 0000815097-20-000020). New parser sections available: ['financial_statements']. This fallback will be removed in v6.0.
TenK falling back to legacy parser for 'Item 3' (filing: 0000815097-20-000020). New parser sections available: ['financial_statements']. This fallback will be removed in v6.0.
TenK falling back to legacy parser for 'Item 7' (filing: 0000815097-20-000020). New parser sections available: ['financial_statements']. This fallback will be removed in v6.0.
TenK falling back to legacy parser for 'Item 7' (filing: 0000815097-20-000020). New parser sections available: ['financial_statements']. This fallback will be removed in v6.0.
Ingesting SEC Corpus: 100%|██████████| 5/5 [12:42<00:00, 152.58s/it]

Raw filing DataFrame shape: (40, 11)

,ticker,year,company,section_1,section_1a,section_3,section_7,section_8,len_1a,len_7,len_3
0,AAPL,2018,Apple Inc.,Item 1.\n\nBusiness\n\nCompany Background\n\nT...,Item 1A.\n\nRisk Factors\n\nThe following disc...,Item 3.\n\nLegal Proceedings\n\nThe Company is...,Item 7.\n\nManagement’s Discussion and Analysi...,Item 8.\n\nFinancial Statements and Supplement...,55472,58061,1359
1,AAPL,2019,Apple Inc.,Item 1.\n\nBusiness\n\nCompany Background\n\nT...,Item 1A.\n\nRisk Factors\n\nThe following disc...,Item 3.\n\nLegal Proceedings\n\nThe Company is...,Item 7.\n\nManagement’s Discussion and Analysi...,Item 8.\n\nFinancial Statements and Supplement...,54994,34310,1348
2,AAPL,2020,Apple Inc.,Item 1. Business\n\nCompany Background\n\nT...,Item 1A. Risk Factors\n\nThe following disc...,Item 3. Legal Proceedings\n\nThe Company is...,Item 7. Management’s Discussion and Analysi...,Item 8. Financial Statements and Supplement...,60994,31977,898

   ticker  year  count
0    AAPL  2018      1
1    AAPL  2019      1
2    AAPL  2020      1
3    AAPL  2021      1
4    AAPL  2022      1
5    AAPL  2023      1
6    AAPL  2024      1
7    AAPL  2025      1
8    AMZN  2018      1
9    AMZN  2019      1
10   AMZN  2020      1
11   AMZN  2021      1
12   AMZN  2022      1
13   AMZN  2023      1
14   AMZN  2024      1
15   AMZN  2025      1
16    CCL  2018      1
17    CCL  2019      1
18    CCL  2020      1
19    CCL  2021      1

## Section 3: Section Parsing
Extract Item 1A (Risk Factors), Item 7 (MD&A), and Item 3 (Legal Proceedings) from filing text.

In [37]:
df_sections = parse_sections(df_filings, target_sections=TARGET_SECTIONS)
print("Parsed sections shape:", df_sections.shape)
display(df_sections.head(5))
display(section_coverage_stats(df_sections))

Parsing sections: 100%|██████████| 40/40 [00:01<00:00, 32.50it/s]

Parsed sections shape: (200, 5)

,ticker,year,section_type,section_text,section_char_len
0,AAPL,2018,section_1,Item 1. Business Company Background The Compan...,30185
1,AAPL,2018,section_1a,Item 1A. Risk Factors The following discussion...,55472
2,AAPL,2018,section_7,Item 7. Management’s Discussion and Analysis o...,58061
3,AAPL,2018,section_3,Item 3. Legal Proceedings The Company is subje...,1359
4,AAPL,2018,section_8,Item 8. Financial Statements and Supplementary...,99155

  section_type  coverage
0    section_1        40
1   section_1a        40
2    section_3        40
3    section_7        40
4    section_8        40

## Section 4: Section-Aware Chunking
Chunk each parsed section independently so chunks never cross section boundaries.

In [38]:
# Define path
cache_file = "data/chunks.pkl"

# Logic: If I changed my taxonomy, I might want to force a refresh
force_refresh = False 

if force_refresh and os.path.exists(cache_file):
    os.remove(cache_file)
    print("Old cache removed to apply new Credit Taxonomy.")

all_chunks = build_chunks(
    df_sections,
    chunk_size=CHUNK_SIZE,
    chunk_overlap=CHUNK_OVERLAP,
    cache_path=cache_file,
    use_multiprocessing=True
)

print("Total chunk count:", len(all_chunks))
display(pd.DataFrame(all_chunks).head(3))
display(chunk_stats(all_chunks))

Chunking sections: 100%|██████████| 200/200 [00:09<00:00, 21.62it/s]

Total chunk count: 2363

,ticker,year,section_type,chunk_id,text,meta_section_len,label
0,AAPL,2018,section_1,AAPL-2018-section_1-0,Item 1. Business Company Background The Compan...,30185,Business Description
1,AAPL,2018,section_1,AAPL-2018-section_1-1,"system, which includes iPad Pro®, iPad and iPa...",30185,Business Description
2,AAPL,2018,section_1,AAPL-2018-section_1-2,"iOS devices and Mac computers, features e-book...",30185,Business Description

        metric    value
0        count  2363.00
1   min_tokens    19.00
2  mean_tokens   765.05
3   max_tokens   800.00

In [39]:
# Convert to DataFrame to verify the new 'len' columns are there
df_chunk_verify = pd.DataFrame(all_chunks)
print("Columns in chunks:", df_chunk_verify.columns.tolist())

Columns in chunks: ['ticker', 'year', 'section_type', 'chunk_id', 'text', 'meta_section_len', 'label']

## Section 5: Embedding
Generate semantic vectors for every chunk and cache to disk.

In [40]:
vectors, vector_metadata = embed_chunks(
    all_chunks,
    model_name=EMBED_MODEL,
    batch_size=256,
    cache_path="data/embeddings.pkl"
)

print("Vectors shape:", getattr(vectors, "shape", None))
print("Embedding info:", embedding_info(vectors))

Loading weights: 100%|██████████| 103/103 [00:00<00:00, 2969.61it/s]
BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
Batches: 100%|██████████| 10/10 [04:37<00:00, 27.76s/it]

Vectors shape: (2363, 384)
Embedding info: {'count': 2363, 'dimension': 384, 'workers': 8}

## Section 6: Hybrid Retrieval
Combine FAISS semantic retrieval with BM25 lexical retrieval using weighted reranking.

In [41]:
retriever = HybridRetriever(
    vectors=vectors,
    metadata=vector_metadata,
    embed_model_name=EMBED_MODEL,
    semantic_weight=0.6,
    lexical_weight=0.4
)

sample_queries = [
    "major macroeconomic risk factors",
    "changes in segment revenue drivers",
    "notable legal proceedings and litigation"
]

for q in sample_queries:
    results = retriever.retrieve(query=q, ticker="TSLA", year=2022, section_type="section_1a", top_k=TOP_K)
    print("\nQuery:", q)
    display(pd.DataFrame(results)[["chunk_id", "semantic_score", "bm25_score", "final_score"]].head(TOP_K))

Loading weights: 100%|██████████| 103/103 [00:00<00:00, 2786.14it/s]
BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Query: major macroeconomic risk factors

                  chunk_id  semantic_score  bm25_score  final_score
0   TSLA-2022-section_1a-0        0.495252    1.000000     0.697151
1  TSLA-2022-section_1a-16        0.095460    0.601519     0.297883
2  TSLA-2022-section_1a-19        0.191694    0.447224     0.293906
3   TSLA-2022-section_1a-6        0.341360    0.154295     0.266534
4  TSLA-2022-section_1a-15        0.303501    0.191353     0.258642
5  TSLA-2022-section_1a-12        0.189795    0.257251     0.216778
6  TSLA-2022-section_1a-11        0.186115    0.257530     0.214681
7  TSLA-2022-section_1a-21        0.329340    0.037738     0.212699
8  TSLA-2022-section_1a-14        0.304083    0.037058     0.197273
9   TSLA-2022-section_1a-8        0.302498    0.037058     0.196322

Query: changes in segment revenue drivers

                  chunk_id  semantic_score  bm25_score  final_score
0  TSLA-2022-section_1a-18        0.250871    1.000000     0.550522
1   TSLA-2022-section_1a-5        0.237557    0.658352     0.405875
2  TSLA-2022-section_1a-21        0.370442    0.000889     0.222621
3  TSLA-2022-section_1a-17        0.306594    0.085026     0.217967
4   TSLA-2022-section_1a-8        0.325019    0.052739     0.216107
5  TSLA-2022-section_1a-14        0.294558    0.057431     0.199707
6   TSLA-2022-section_1a-2        0.276392    0.046807     0.184558
7  TSLA-2022-section_1a-12        0.244391    0.063051     0.171855
8  TSLA-2022-section_1a-10        0.285853    0.000000     0.171512
9  TSLA-2022-section_1a-15        0.276199    0.010216     0.169806

Query: notable legal proceedings and litigation

                  chunk_id  semantic_score  bm25_score  final_score
0  TSLA-2022-section_1a-19        0.162971    1.000000     0.497783
1  TSLA-2022-section_1a-16        0.233935    0.624004     0.389962
2  TSLA-2022-section_1a-18        0.185492    0.672231     0.380187
3  TSLA-2022-section_1a-15        0.147765    0.617939     0.335835
4  TSLA-2022-section_1a-20        0.183737    0.510054     0.314264
5  TSLA-2022-section_1a-17        0.034612    0.626040     0.271183
6  TSLA-2022-section_1a-12        0.262390    0.006424     0.160004
7  TSLA-2022-section_1a-10        0.153538    0.119166     0.139789
8  TSLA-2022-section_1a-11        0.103814    0.115235     0.108382
9   TSLA-2022-section_1a-5        0.082429    0.121907     0.098220

In [42]:
# Example Query updated for Credit Analysis
query = "Identify changes in debt maturity, liquidity risks, and management tone regarding credit facilities."
results = retriever.retrieve(query, ticker="CCL", top_k=TOP_K)

In [43]:
results

[{'ticker': 'CCL',
  'year': 2025,
  'section_type': 'section_7',
  'chunk_id': 'CCL-2025-section_7-9',
  'source': 'CCL_2025_10k',
  'text': 'as well as estimated interest payments and does not include the impact of any future possible refinancings. Excludes undrawn export credits. (b)As of November 30, 2024, we have undrawn export credit facilities of $7.8 billion which fund a portion of our newbuild contractual commitments. Funding Sources As of November 30, 2024, we had $4.2 billion of liquidity including $1.2 billion of cash and cash equivalents and $2.9 billion of borrowings available under our Revolving Facility. In addition, we had $7.8 billion of undrawn export credit facilities to fund ship deliveries planned through 2033. We plan to use existing liquidity and future cash flows from operations to fund our cash requirements including capital expenditures not funded by our export credit facilities. We seek to manage our credit risk exposures, including counterparty nonperformance associated with our cash and cash equivalents, and future financing facilities by conducting business with well-established financial institutions, and export credit agencies and diversifying our counterparties. (in billions)20252026202720282029Thereafter Future export credit facilities at November 30, 2024 $0.7 $— $1.2 $1.2 $1.6 $3.1 Our export credit facilities contain various financial covenants as described in Note 5 - “Debt.” At November 30, 2024, we were in compliance with the applicable covenants under our debt agreements.',
  'meta_section_len': 36440,
  'label': 'MD&A',
  'semantic_score': 0.49490904808044434,
  'bm25_score': np.float64(0.9784159591864006),
  'final_score': np.float64(0.6883118125228268)},
 {'ticker': 'CCL',
  'year': 2021,
  'section_type': 'section_1a',
  'chunk_id': 'CCL-2021-section_1a-7',
  'source': 'CCL_2021_10k',
  'text': 'will be able to obtain amendments in a timely manner, on acceptable terms or at all. If we were not able to obtain the financial covenant amendments described above under any one or more of these debt facilities, we would be in default of any such agreement. As a consequence, we would need to refinance or repay the applicable debt facility or facilities, and would be required to raise additional debt or equity capital, or divest assets, to refinance or repay such facility or facilities. If we were to be unable to obtain financial covenant amendments as may be required under any one or more of these debt facilities, there can be no assurance that we would be able to raise sufficient debt or equity capital, or divest assets, to refinance or repay such facility or facilities. With respect to each of the unfunded debt facilities, if we were unable to obtain amendments under such debt facilities, the relevant lender under such facility could terminate that facility. With respect to each of our funded debt facilities, if we were unable to obtain amendments or refinance or repay such debt facilities, it would lead to an event of default under such facilities, which could lead to an acceleration of the indebtedness under such debt facilities. In turn, this would lead to an event of default and potential acceleration of amounts due under all of our outstanding debt and derivative contract payables. As a result, the failure to obtain the financial covenant amendments described above would have a material adverse effect. h. The covenants in certain of our debt facilities may require us to secure those facilities in the future. Certain of our debt facilities contain provisions which may require that we provide a security interest in certain assets. In certain of our debt facilities, there is a requirement that if the credit rating of our senior indebtedness should fall below investment 32 grade (which occurred on June 24, 2020) and at such time we have granted liens or security interests in respect of indebtedness in an amount exceeding 25% of our total assets (excluding for these purposes the value of any intangible assets) as shown in our most recent Consolidated Balance Sheet, then we will be required to provide a first-priority security interest in certain designated assets. In addition, under our export credit facilities, there is a requirement that if a security interest or lien is granted in respect of a vessel to secure borrowed money under certain other debt facilities, then a first-priority security interest will be required to be provided over certain designated vessels. If the events described above were to occur, we may be unable to comply with this requirement and expect to seek covenant amendments from the lenders under the relevant facilities. Any such amendment may lead to increased costs, increased interest rates, additional restrictive covenants and other available lender protections that would be applicable to us under these debt facilities, and such increased costs, restrictions and modifications may vary among debt facilities. Our ability to give additional lender protections under these facilities, including the granting of security interests in collateral, will be limited by the restrictions in our indebtedness and security interest we have already granted. If we were not able to obtain amendments, the occurrence of such events may result in an event of default under these facilities and other debt facilities that contain cross default provisions that would be triggered. Operating Risk Factors a.World events impacting the ability or desire of people to travel have and may continue to lead to a decline in demand for cruises. We have been and may continue to be impacted by the public’s concerns regarding the health, safety and security of travel, including government travel advisories and travel restrictions, political instability and civil unrest, terrorist attacks and other general concerns. Additionally, we have been and may continue to be impacted by heightened regulations around customs and border control, travel bans to and from certain geographical areas, government policies increasing the difficulty of travel and limitations on issuing international travel visas. We may also be impacted by adverse changes in the perceived or actual economic climate, such as global or regional recessions, higher unemployment and underemployment rates and declines in income levels. Furthermore, uncertainties resulting from the UK’s exit from the EU may impact our business. b. Incidents concerning our ships, guests or the cruise vacation industry as well as adverse weather conditions and other natural disasters have in the past and may, in the future, impact the satisfaction of our guests and crew and lead to reputational damage. Our operations involve the risk of incidents and media coverage thereof. Such incidents include, but are not limited to, the improper operation or maintenance of ships, motorcoaches and trains; guest',
  'meta_section_len': 46573,
  'label': 'Risk Factors',
  'semantic_score': 0.5496099591255188,
  'bm25_score': np.float64(0.8914699422402194),
  'final_score': np.float64(0.6863539523713991)},
 {'ticker': 'CCL',
  'year': 2021,
  'section_type': 'section_1a',
  'chunk_id': 'CCL-2021-section_1a-6',
  'source': 'CCL_2021_10k',
  'text': 'credit facilities extend through November 30, 2021 or December 31, 2021, with the testing under such facilities recommencing on the February 28, 2022 testing date. Even though we expect to obtain further amendments under our export credit facilities with respect to the Financial Covenant (in particular in light of the additional debt holiday amendments that have been introduced by the European export credit agencies), if such amendments are not obtained we may not be in compliance with the Financial Covenant following November 30, 2021 with the next testing date of February 28, 2022 under our export credit facilities, or in future periods for certain agreements because of the pause and limited resumptions of our guest operations. In addition, under the terms of certain of our debt facilities, we are required to ensure that our debt as a percentage of capital does not exceed 65% at the end of each fiscal quarter (the “Debt to Capital Covenant”). While we were in compliance with the Debt to Capital Covenant as of November 30, 2020, we have entered into agreements to amend the Revolving Facility and the agreements governing our bank loans to increase the Debt to Capital Covenant to 75% for each quarterly testing date from November 30, 2021 to May 31, 2023, and thereafter declining ratably to 65% for the May 31, 2024 testing date and thereafter. We are in the process of negotiating similar amendments to our funded export credit facilities (with aggregate indebtedness of $7.3 billion as of November 30, 2020) and our unfunded export credit facilities (which had an aggregate principal amount of $8.0 billion as of November 30, 2020) to obtain amendments under the Debt to Capital Covenant (compliance with which is currently waived through November 30, 2021 or December 31, 2021, as applicable, with the next testing date of February 28, 2022). Even though we expect to obtain amendments under our export credit facilities with respect to the Debt to Capital Covenant (in particular in light of the additional debt holiday amendments that have been introduced by the European export credit agencies), if such amendments are not obtained we may be required to take certain actions, such as issuing additional equity and/or reducing our indebtedness, failing which we may not be in compliance with the Debt to Capital Covenant as of the February 28, 2022 testing date under our export credit facilities, or as of future testing dates for certain agreements, because of the pause and limited resumptions of our guest operations. The Financial Covenant and Debt to Capital Covenant amendments have led and may continue to lead to increased costs, increased interest rates, additional restrictive covenants and other lender protections that are, or may become, applicable to us under these debt facilities, and such increased costs, restrictions and modifications may vary among debt facilities. For example, in connection with the amendments to the Revolving Facility and agreements governing our bank loans described above, we have made certain changes to more closely align the financial covenants among the various facilities and agreements. In addition, we have agreed to additional restrictive covenants in such facilities and agreements with respect to debt incurrence, lien incurrence, restricted payments and investments that are substantially consistent with those contained in the indenture governing the 2026 Senior Unsecured Notes. Our ability to provide additional lender protections under these facilities, including the granting of security interests in certain collateral and the granting of guarantees with respect to certain outstanding debt, will be limited by the terms of such agreements as amended, and our other debt facilities. There can be no assurance that we will be able to obtain amendments in a timely manner, on acceptable terms or at all. If we were not able to obtain the financial covenant amendments described above under any one or more of these debt facilities, we would be in default of any such agreement. As a consequence, we would need to refinance or repay the applicable debt facility or facilities, and would be required to raise additional debt or equity capital, or divest assets, to refinance or repay such facility or facilities. If we were to be unable to obtain financial covenant amendments as may be required under any one or more of these debt facilities, there can be no assurance that we would be able to raise sufficient debt or equity capital, or divest assets, to refinance or repay such facility or facilities. With respect to each of the unfunded debt facilities, if we were unable to obtain amendments under such debt facilities, the relevant lender under such facility could terminate that facility. With respect to each of our funded debt facilities, if we were unable to obtain amendments or refinance or repay such debt facilities, it would lead to an event of default under such',
  'meta_section_len': 46573,
  'label': 'Risk Factors',
  'semantic_score': 0.5564976930618286,
  'bm25_score': np.float64(0.8561438959572635),
  'final_score': np.float64(0.6763561742200026)},
 {'ticker': 'CCL',
  'year': 2023,
  'section_type': 'section_1a',
  'chunk_id': 'CCL-2023-section_1a-9',
  'source': 'CCL_2023_10k',
  'text': 'a material adverse effect as described above. Refer to Note 5 - Debt for additional information. e. Our variable rate indebtedness exposes us to interest rate volatility, which could cause our debt service obligations to increase significantly. Borrowings under certain of our facilities are at variable rates of interest and expose us to interest rate volatility. As interest rates increase, our debt service obligations on certain of our variable rate indebtedness will increase even though the amount borrowed remains the same, and our net income and cash flows, including cash available for servicing our indebtedness, will correspondingly decrease. At the end of 2021, the ICE Benchmark Administration, the administrator for London Interbank Offered Rate (“LIBOR”), ceased publishing one-week and two-month U.S. dollar LIBOR and will cease publishing all remaining U.S. dollar LIBOR tenors in mid-2023. Concurrently, the United Kingdom’s Financial Conduct Authority announced the cessation or loss of representativeness of the U.S. dollar LIBOR tenors from those dates. The U.S. Federal Reserve, in conjunction with the Alternative Reference Rates Committee, a steering committee comprised of, among other entities, large U.S. financial institutions, has recommended replacing U.S. dollar LIBOR with a new index that measures the cost of borrowing cash overnight, backed by U.S. Treasury securities (“SOFR”). SOFR is observed and backward-looking, which stands in contrast with LIBOR, which is an estimated forward-looking rate and relies, to some degree, on the expert judgment of submitting panel members. While we continue to monitor market developments to assess replacement rate options, the consequences of these developments with respect to LIBOR cannot be entirely predicted and may result in the level of interest payments on the portion of our indebtedness that bears interest at variable rates to be affected, which may adversely impact the amount of our interest payments under such debt. 45 f. The covenants in certain of our export credit facilities may require us to secure those facilities in the future. Our export credit facilities contain provisions which may require that we provide a security interest in certain assets and in particular the relevant vessels that are the subject matter of those financings (or a comparable vessel). In certain of our export credit facilities, there is a requirement that if the credit rating of our senior indebtedness falls below investment grade (which occurred on June 24, 2020 and remained the case as of November 30, 2022) and at such time we have granted liens or security interests in respect of indebtedness exceeding 25% of our total assets (excluding for these purposes the value of any intangible assets) as shown in our most recent Consolidated Balance Sheet, we will be required to provide a first-priority security interest in the relevant vessel that is the subject matter of that export credit facility (or a comparable vessel). In addition, under all our export credit facilities, there is also a requirement that if a security interest or lien is granted in respect of a vessel to secure borrowed money under any other export credit facility, then a first-priority security interest may be required to be provided over the relevant vessel which is the subject matter of that export credit facility (or a comparable vessel). If the events described above were to occur, we may be unable to comply with this requirement and would expect to seek covenant amendments from the lenders under the relevant facilities. Any such amendment may lead to increased costs, increased interest rates, additional restrictive covenants and other available lender protections that would be applicable to us under these debt facilities, and such increased costs, restrictions and modifications may vary among debt facilities. Our ability to give additional lender protections under these facilities, including the granting of security interests in collateral, will be limited by the restrictions in our indebtedness and security interest we have already granted. If we were not able to obtain amendments, the occurrence of such events may result in an event of default under these facilities and other debt facilities that contain cross default provisions that would be triggered. Cautionary Note Concerning Factors That May Affect Future Results Some of the statements, estimates or projections contained in this document are “forward-looking statements” that involve risks, uncertainties and assumptions with respect to us, including some statements concerning future results, operations, outlooks, plans, goals, reputation, cash flows, liquidity and other events which have not yet occurred. These statements are intended to qualify for the safe harbors from liability provided by Section 27A of the Securities Act of 1933 and Section 21E of the Securities Exchange Act of 1934, as amended. All statements other than statements of historical facts are statements that could be deemed forward-looking. These statements are based on current expectations, estimates, forecasts and projections about our business and the industry in which we operate and the beliefs and assumptions',
  'meta_section_len': 43298,
  'label': 'Risk Factors',
  'semantic_score': 0.4180665612220764,
  'bm25_score': np.float64(1.0),
  'final_score': np.float64(0.6508399367332458)},
 {'ticker': 'CCL',
  'year': 2024,
  'section_type': 'section_7',
  'chunk_id': 'CCL-2024-section_7-9',
  'source': 'CCL_2024_10k',

## Section 7: Comparative Reasoning
Retrieve evidence from two filing years and ask GPT-4o for structured differences.

In [60]:
comparison_result = compare(
    retriever=retriever,
    ticker="CCL",
    section_type="section_1a",
    year_a=2020,
    year_b=2025,
    query="material risk changes over time",
    top_k=TOP_K,
    model=LLM_MODEL
)

print("Raw diff output:")
print(comparison_result.get("raw_diff", "")[:3000])

Raw diff output:
### Delta Analysis of SEC Filings for CCL (2020 vs 2025)

#### 1. BUSINESS FRAGILITY
- **Customer Concentration**: No significant changes detected in customer concentration from 2020 to 2025.
- **Supply Chain Shifts**:
  - **2020**: Mentioned potential delays or cancellations of cruises due to supply chain issues (chunk_id=CCL-2020-section_1a-2).
  - **2025**: Expanded on supply chain issues, emphasizing reliance on suppliers and potential disruptions (chunk_id=CCL-2025-section_1a-6). This indicates an increased fragility in the supply chain.
- **Competitive Pressure**: No explicit mention of competitive pressure in either year.

#### 2. RISK INTENSITY
- **New Risk Factors**:
  - **2025** introduces risks related to cybersecurity and data privacy breaches (chunk_id=CCL-2025-section_1a-3), which were not present in 2020.
- **Expanded Risk Language**:
  - **2025** includes more detailed language regarding climate change and regulatory impacts (chunk_id=CCL-2025-section_1a-5), indicating an escalation in risk language.
- **Regulatory Escalation**:
  - **2025** discusses increased regulatory focus on climate change and emissions (chunk_id=CCL-2025-section_1a-5), which was less emphasized in 2020.

#### 3. LIQUIDITY STRESS
- **Phrases Indicating Stress**:
  - **2025** mentions the significant cash requirement to service debt and sustain operations (chunk_id=CCL-2025-section_1a-7), indicating potential liquidity stress.
- **Refinancing Risk**:
  - **2025** highlights risks associated with high debt levels and potential covenant breaches (chunk_id=CCL-2025-section_1a-7), suggesting refinancing risk.
- **Capital Allocation Shifts**: No explicit mention of capital allocation shifts in either year.

#### 4. MANAGEMENT TONE
- **Increased Hedging Language**:
  - **2025** shows a more cautious tone regarding operational risks and external factors impacting business (chunk_id=CCL-2025-section_1a-0).
- **Specificity Shifts**:
  - The language in **2025** is more specific regarding risks (e.g., cybersecurity, climate change) compared to the more general statements in **2020**.
- **Sentiment Decay**: The overall tone in **2025** reflects increased caution and concern compared to **2020**, indicating sentiment decay.

#### 5. CROSS-SECTION CONTRADICTIONS
- **Management Optimism vs. Risk Disclosures**:
  - In **2025**, there is a notable contradiction between the optimistic outlook on recovery and the detailed risk disclosures regarding debt and operational challenges (chunk_id=CCL-2025-section_1a-7). This indicates a potential mismatch between management's optimistic projections and the underlying risks.

### Fair Value Analysis
- **Decrease in Fair Value**: If a decrease in the 'Fair Value' of debt is detected in Item 8, it is crucial to cross-check Item 7 (MD&A) and Item 1A (Risk) for terms like 'liquidity', 'refinancing', 'covenant', or 'facility access'.
  - **2025** indicates significant cash requirements and potential covenant breaches (chunk_id=CCL

## Section 8: Structured Output Generation
Convert reasoning output into strict JSON schema and validate it with graceful error handling.

In [61]:
structured_output = generate_structured_output(comparison_result, model=LLM_MODEL)

if "error" in structured_output:
    print("Structured output failed gracefully:")
    print(json.dumps(structured_output, indent=2))
else:
    print("Validated structured JSON output:")
    print(json.dumps(structured_output, indent=2)[:5000])

Validated structured JSON output:
{
  "executive_summary": "CCL's risk landscape has evolved from 2020 to 2025, with increased supply chain fragility, new cybersecurity risks, and indications of potential liquidity stress, leading to a cautious outlook.",
  "findings": [
    {
      "category": "STRATEGIC",
      "materiality": "MEDIUM",
      "title": "Increased Supply Chain Risks",
      "evidence": "Expanded on supply chain issues, emphasizing reliance on suppliers and potential disruptions.",
      "verdict": "Classified as MEDIUM MATERIALITY due to strategic shifts in supply chain management.",
      "source": "CCL-2025-section_1a-6"
    },
    {
      "category": "REGULATORY",
      "materiality": "MEDIUM",
      "title": "New Cybersecurity Risks",
      "evidence": "Introduces risks related to cybersecurity and data privacy breaches.",
      "verdict": "Classified as MEDIUM MATERIALITY due to the introduction of new risk factors.",
      "source": "CCL-2025-section_1a-3"
    },
    {
      "category": "REGULATORY",
      "materiality": "MEDIUM",
      "title": "Expanded Regulatory Language",
      "evidence": "Includes more detailed language regarding climate change and regulatory impacts.",
      "verdict": "Classified as MEDIUM MATERIALITY due to increased regulatory focus.",
      "source": "CCL-2025-section_1a-5"
    },
    {
      "category": "FINANCIAL",
      "materiality": "MARKET",
      "title": "Potential Liquidity Stress",
      "evidence": "Mentions significant cash requirement to service debt and sustain operations.",
      "verdict": "Classified as MARKET MATERIALITY due to mark-to-market debt value changes.",
      "source": "CCL-2025-section_1a-7"
    },
    {
      "category": "FINANCIAL",
      "materiality": "HIGH",
      "title": "Refinancing Risk",
      "evidence": "Highlights risks associated with high debt levels and potential covenant breaches.",
      "verdict": "Classified as HIGH MATERIALITY due to potential covenant breaches exceeding 10% of cash reserves.",
      "source": "CCL-2025-section_1a-7"
    },
    {
      "category": "GOVERNANCE",
      "materiality": "LOW",
      "title": "Management Tone Shift",
      "evidence": "Shows a more cautious tone regarding operational risks and external factors.",
      "verdict": "Classified as LOW MATERIALITY as it does not indicate a significant change in governance.",
      "source": "CCL-2025-section_1a-0"
    },
    {
      "category": "GOVERNANCE",
      "materiality": "LOW",
      "title": "Cross-Section Contradictions",
      "evidence": "Notable contradiction between optimistic outlook on recovery and detailed risk disclosures.",
      "verdict": "Classified as LOW MATERIALITY as it reflects internal management dynamics without immediate financial impact.",
      "source": "CCL-2025-section_1a-7"
    }
  ],
  "strategic_outlook": {
    "primary_driver": "Increased refinancing risk due to high debt levels and potential covenant breaches.",
    "net_posture": "CAUTIONARY",
    "liquidity_buffer": "Liquidity stress indicated, with potential covenant breaches suggesting a need for close monitoring."
  }
}

## Section 9: Evaluation
Evaluate retrieval and structured generation quality. Include ablation-style comparison table.

In [62]:
test_years = list(range(YEAR_RANGE[0], YEAR_RANGE[1] + 1))
test_set = build_test_set(tickers=TICKERS, years=test_years)
eval_results = run_retrieval_eval(retriever, test_set, top_k=TOP_K)

# Aggregate core retrieval metrics.
summary = pd.DataFrame({
    "Recall@5": [eval_results["Recall@5"].mean()],
    "MRR": [eval_results["MRR"].mean()]
})

print("Retrieval evaluation summary:")
display(summary)

# Real ablation: re-runs eval with BM25 and metadata filtering toggled off.
ablations = ablation_table(retriever, test_set, top_k=TOP_K)
display(ablations)

# Structured output and citation quality checks from one sample output.
from src.evaluate import citation_grounding_score, structured_output_accuracy

if isinstance(structured_output, dict) and "error" not in structured_output:
    cg = citation_grounding_score(structured_output)
    sa = structured_output_accuracy(structured_output)
else:
    cg, sa = 0.0, 0.0

print({
    "Citation Grounding Score": cg,
    "Structured Output Accuracy": sa
})

Running retrieval eval: 100%|██████████| 20/20 [00:02<00:00,  6.93it/s]

Retrieval evaluation summary:

   Recall@5  MRR
0      0.95  0.9

Hybrid + Metadata Filter: 100%|██████████| 20/20 [00:02<00:00,  8.40it/s]
No BM25 (Semantic Only): 100%|██████████| 20/20 [00:02<00:00,  7.86it/s]
No Metadata Filtering: 100%|██████████| 20/20 [00:05<00:00,  3.50it/s]
Semantic Only, No Filter: 100%|██████████| 20/20 [00:00<00:00, 24.93it/s]

                      setup  Recall@5   MRR
0  Hybrid + Metadata Filter      0.95  0.90
1   No BM25 (Semantic Only)      0.95  0.85
2     No Metadata Filtering      1.00  1.00
3  Semantic Only, No Filter      1.00  1.00

{'Citation Grounding Score': 0.0, 'Structured Output Accuracy': 0.0}

## Section 10: Streamlit App
The full pipeline is wired in app.py for deployment on Streamlit Community Cloud.

In [ ]:
# Run this command in terminal (not inside notebook):
# streamlit run app.py

print("Streamlit app entrypoint: app.py")
print("UI includes ticker, years, section, spinner, structured output, and raw JSON toggle.")